### ISSUE TITLE
MargarineBot Cannot Delete Files

### ISSUE THREAD

**Issue by FrenzY8** [Butterstroke/MargarineBot#76]
Error: EPERM: operation not permitted, unlink 'c:\MargarineBot-master/node_modules/klasa/src/commands/General/Chat Bot Info'
    at unlinkSync (fs.js:1251:3)
    at c:\MargarineBot-master\utilities\utilExport.js:18:4
    at Array.forEach (<anonymous>)
    at exports.commandRemover (c:\MargarineBot-master\utilities\utilExport.js:17:28)
    at Object.<anonymous> (c:\MargarineBot-master\index.js:40:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'c:\\MargarineBot-master/node_modules/klasa/src/commands/General/Chat Bot Info'
}

**Comment by AurelicButter** [comment]
It's not a new bug, more of a potential limitation of your environment. This error typically occurs when the program cannot manage the files in the directory. On startup, Margarine has to remove some files in the Klasa install before it can run since it causes conflict issues during use. 

Can you manage your node_modules folder?

**Comment by AurelicButter** [comment]
Hearing nothing in the past few days, I'll assume that this is taken care of and close the issue. Feel free to reach out again if needed.
